// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGdZKfTD94Kc2IOBGbGrnEI6q0j7uvZOI',
    appId: '1:170510013649:web:ca8a09b2d96171cd2ca1f0',
    messagingSenderId: '170510013649',
    projectId: 'task-management-app-95f35',
    authDomain: 'task-management-app-95f35.firebaseapp.com',
    storageBucket: 'task-management-app-95f35.firebasestorage.app',
    measurementId: 'G-NBWLCPVH6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WvjuRy_CcNR7BHpZec7rSLat9tMcvHo',
    appId: '1:170510013649:android:dec7ec9502199e142ca1f0',
    messagingSenderId: '170510013649',
    projectId: 'task-management-app-95f35',
    storageBucket: 'task-management-app-95f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByias_ptvnO-p2MxZUEhQz6YnAKVX3bHM',
    appId: '1:170510013649:ios:e421fe8a94dadb2d2ca1f0',
    messagingSenderId: '170510013649',
    projectId: 'task-management-app-95f35',
    storageBucket: 'task-management-app-95f35.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByias_ptvnO-p2MxZUEhQz6YnAKVX3bHM',
    appId: '1:170510013649:ios:e421fe8a94dadb2d2ca1f0',
    messagingSenderId: '170510013649',
    projectId: 'task-management-app-95f35',
    storageBucket: 'task-management-app-95f35.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGdZKfTD94Kc2IOBGbGrnEI6q0j7uvZOI',
    appId: '1:170510013649:web:20de533228e17baf2ca1f0',
    messagingSenderId: '170510013649',
    projectId: 'task-management-app-95f35',
    authDomain: 'task-management-app-95f35.firebaseapp.com',
    storageBucket: 'task-management-app-95f35.firebasestorage.app',
    measurementId: 'G-Q08YG7S81F',
  );
}
